networks:
  infra-network:
    external: true

volumes:
  nexus3-72-data:
    external: true

services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3:3.76.0
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - nexus3-72-data:/nexus-data
    networks:
      - infra-network
